### ISSUE TITLE
Why was `loads()` method removed?

### ISSUE THREAD

**Issue by mrmachine** [imbolc/asjson#1]
This broke https://github.com/imbolc/jsondict

**Comment by imbolc** [comment]
I'm sorry, didn't expect somebody else using it :) I added serializing of
`bson.ObjectId` and I don't know how to parse it back. Maybe you have an
idea?

**Comment by mrmachine** [comment]
Sorry, I don't. But there's not much point in serialising something you can't deserialise, is there?

**Comment by imbolc** [comment]
I mostly use it to serialize web api responses. And then deserialize these
responses with js. Of course, you can do it with python to. I mean I don't
know any way to do it automatically in common case.

Even deserealizing of datetime was not explicit in v0.1. I mean
`dumps(date(2015-01-01))` was equal `dumps('2015-01-01Z'). So what type
should return`loads('2015-01-01Z')` datetime or string?
